export function repoRoot(): string;
export function jumpyGoatHqHome(): string;
export function automationsDir(): string;
export function agentsDir(): string;
export function agentDir(name: string): string;
export function agentPath(name: string): string;
export function agentContextDir(name: string): string;
export function dataDir(): string;
export function settingsDir(): string;
export function settingsPath(): string;
export function workspacesDir(): string;
export function workspaceDir(name: string): string;
export function tracesDir(): string;
export function dbPath(): string;
export function automationPath(name: string): string;
export function boardsDir(): string;
export function boardDir(name: string): string;
export function boardPath(name: string): string;
export function tasksDir(board: string): string;
export function taskPath(board: string, id: string): string;
export const projectsDir: typeof boardsDir;
export const projectDir: typeof boardDir;
export const projectPath: typeof boardPath;
