export {
  agentContextDir,
  agentDir,
  jumpyGoatHqHome,
  agentPath,
  agentsDir,
  automationPath,
  automationsDir,
  boardDir,
  boardPath,
  boardsDir,
  dataDir,
  dbPath,
  projectDir,
  projectPath,
  projectsDir,
  repoRoot,
  settingsDir,
  settingsPath,
  taskPath,
  tasksDir,
  tracesDir,
  workdirPath,
  workdirsDir,
} from "../../shared/paths.js";
