export {
  agentContextDir,
  agentDir,
  agenthqHome,
  agentPath,
  agentsDir,
  automationPath,
  automationsDir,
  dataDir,
  dbPath,
  projectDir,
  projectPath,
  projectsDir,
  repoRoot,
  taskPath,
  tasksDir,
  tracesDir,
  workspaceDir,
  workspacesDir,
} from "../../shared/paths.js";
